version: "3"

services:
  ckan-dev:
    restart: always
    build:
      context: ckan/
      dockerfile: Dockerfile.dev.dept-of-ed
      args:
        - TZ=UTC
    env_file:
      - .env.dept-of-ed
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      # debug extensions
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-harvest:/srv/app/src_extensions/ckanext-harvest
      - /home/hudson/dev/datopian/ckan-and-exts/datopian-ckanext-datajson:/srv/app/src_extensions/ckanext-datajson
      - /home/hudson/dev/datopian/DepOfEd/ca-ckanext-ed:/srv/app/src_extensions/ckanext-ed
      - /home/hudson/dev/datopian/DepOfEd/ca-ckanext-collections:/srv/app/src_extensions/ckanext-collections
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-pages:/srv/app/src_extensions/ckanext-pages
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-showcase:/srv/app/src_extensions/ckanext-showcase
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-googleanalytics:/srv/app/src_extensions/ckanext-googleanalytics
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-hierarchy:/srv/app/src_extensions/ckanext-hierarchy
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-geoview:/srv/app/src_extensions/ckanext-geoview
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-pdfview:/srv/app/src_extensions/ckanext-pdfview
      - /home/hudson/dev/datopian/ckan-and-exts/ckanext-ga-report:/srv/app/src_extensions/ckanext-ga-report

  db:
    restart: always
    container_name: db
    env_file:
      - .env.dept-of-ed
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine
  
  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

volumes:
  ckan_storage:
  pg_data:
  solr_data:
