version: "3"

services:

  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev.nhs
      args:
        - TZ=UTC
    env_file:
      - .env.nhs
    links:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
      # debug extensions
      - /home/hudson/dev/datopian/nhs/nhs:/srv/app/src_extensions/ckanext-nhs
      - /home/hudson/dev/datopian/nhs/ckanext-dataexplorer:/srv/app/src_extensions/ckanext-dataexplorer

  db:
    container_name: db
    env_file:
      - .env.nhs
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
